/* eslint-disable @next/next/no-img-element */
import Navbar from "@/components/Other/Navbar"
import About from "@/components/Section/About"
import Blog from "@/components/Section/Blog"
import Service from "@/components/Section/Service"
import DetailProject from "@/constants/DetailProject"
import { blog } from "@/constants/blog"
import { serviceData } from "@/constants/home"
import Head from "next/head"
import { Fragment } from "react"

import "slick-carousel/slick/slick.css"
import "slick-carousel/slick/slick-theme.css"
import SliderCarousel from "@/components/slider"
import BackToTopButton from "@/components/back-to-top-button"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Fragment>
        <div className="overflow-hidden" id="home">
          <div className="position-relative">
            <SliderCarousel />
            <div className="wrapper__bg-head"></div>
            <Navbar />
            <section className="position-relative z-2">
              <div className="container">
                <div className="text-center">
                  <h1 className="semi-bold font__size--90 text__90-1024 text__90-md text__90-sm text__90-xs  color__white text-uppercase mb-0">
                    Welcome to <br className="d-none d-sm-block " /> Mandiri
                    Trans Utama
                  </h1>
                  <p className="medium roboto font__size--16 text__16-1024 color__white my-4">
                    Jl. Jend. Sudirman Raya Bekasi Km. 32 Harapan Mulya, Medan
                    Satria tortor <br className="d-none d-sm-block" /> Kota
                    Bekasi, West Java, 17143 Indonesia
                  </p>
                  <div className="div flex-wrap flex-sm-nowrap align-items-center justify-content-center"></div>
                </div>
              </div>
            </section>
          </div>
          <About />
          <Service service={serviceData} type="home" />
          <Blog blog={blog} title={"news & articles"} top={"latest blog"} />
          <DetailProject />
        </div>
      </Fragment>
      <BackToTopButton />
    </>
  )
}
