/* eslint-disable @next/next/no-img-element */
import Navbar from "@/components/Other/Navbar";
import About from "@/components/Section/About";
import Blog from "@/components/Section/Blog";
import Service from "@/components/Section/Service";
import DetailProject from "@/constants/DetailProject";
import { blog } from "@/constants/blog";
import Head from "next/head";
import Link from "next/link";
import { Fragment } from "react";

const serviceData = [
  {
    img: "./../images/project/tesproject.JPG",
    title: "Petroleum & Gas Energy",
    desc: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
  },
  {
    img: "./../images/Image (5).png",
    title: "Construction & Engineering",
    desc: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
  },
  {
    img: "./../images/Image (6).png",
    title: "Auto & Mechanical Engineering",
    desc: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
  },
  {
    img: "./../images/ds (1).png",
    title: "Petroleum & Gas Energy",
    desc: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
  },
  {
    img: "./../images/ds (3).png",
    title: "Construction & Engineering",
    desc: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
  },
  {
    img: "./../images/ds (2).png",
    title: "Auto & Mechanical Engineering",
    desc: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Fragment>
        <div className="overflow-hidden">
          <div className="position-relative">
            <img src="/images/TES2.JPG" className="images__wrap-head" alt="" />
            <div className="wrapper__bg-head"></div>
            <Navbar />
            <section className="position-relative z-2">
              <div className="container">
                <div className="text-center">
                  <h1 className="semi-bold font__size--90 text__90-1024 text__90-md text__90-sm text__90-xs  color__white text-uppercase mb-0">
                    Welcome to <br className="d-none d-sm-block " /> Mandiri
                    Trans Utama
                  </h1>
                  <p className="medium roboto font__size--16 text__16-1024 color__white my-4">
                    Jl. Jend. Sudirman Raya Bekasi Km. 32 Harapan Mulya, Medan
                    Satria tortor <br className="d-none d-sm-block" /> Kota
                    Bekasi, West Java, 17143 Indonesia
                  </p>

                  <div className="div flex-wrap flex-sm-nowrap align-items-center justify-content-center">
                    <button className="btn__mm-w-60 semi-bold rounded-0 font__size--14 text__14-1024 btn btn__orange shadow color__white text-uppercase">
                      Discover More
                    </button>
                    <Link href="/service">
                      <button className="btn__mm-w-60 semi-bold font__size--14 text__14-1024 btn btn__outlined--white color__white no__opacity h__black rounded-0 shadow text-uppercase mt-3 mt-sm-0 ml-sm-4">
                        our service
                      </button>
                    </Link>
                  </div>
                </div>
              </div>
            </section>
          </div>
          <About />
          <Service service={serviceData} type="home" />
          <section className="overflow-hidden">
            <div className="text-center mb-5">
              <p className="semi-bold font__size--14 text__14-1024 color__orange text-uppercase">
                our work
              </p>
              <h3 className="bold font__size--58 text__50-1024 text__50-sm text__50-xs text-uppercase">
                Construction Projects
              </h3>
            </div>
            {/* <SliderConstruction /> */}
          </section>

          <Blog blog={blog} title={"news & articles"} top={"latest blog"} />
          {/* <Contact />

        <Footer /> */}
          <DetailProject />
        </div>
      </Fragment>
    </>
  );
}
